/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 boot.gltf --transform
Author: inciprocal (https://sketchfab.com/inciprocal.com)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pink-winter-boot-89783e744f7249ffa9eedcee69c760ee
Title: Pink Winter Boot
*/
import React from 'react'
import { OrbitControls, Stage } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export default function Boot(props) {
  const { nodes, materials } = useGLTF('/boot-transformed.glb')
  return (
    <>
    <Canvas>
        <Stage environment="city" intensity={0.6}>
          <group {...props} dispose={null}>
            <mesh geometry={nodes.Object_2.geometry} material={materials.sh_pinkSnowBoot} position={[-0.03, 0, 0.02]} rotation={[-Math.PI / 2, 0, -0.51]} />
          </group>
        </Stage>
        <OrbitControls enableZoom={false}>
        </OrbitControls>
    </Canvas>
    <p className='hidden md:block w-52 h-20 p-2 bg-white rounded absolute bottom-24 right-2 text-xs text-black font-thin'>We design products with a strong focus on both world class design and ensure your product is a market success.</p>
    </>
  )
}

useGLTF.preload('/boot-transformed.glb')
