/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 react.gltf --transform
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
Title: React logo
*/

import React from 'react'
import { OrbitControls, Stage} from '@react-three/drei'
import { Canvas } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export default function ReactLogo(props) {
  const { nodes, materials } = useGLTF('/react-transformed.glb')
  return (
    <>
    <Canvas>
    <Stage environment="city" intensity={0.6}>
      <group {...props} dispose={null}>
        <group scale={0.01}>
          <mesh geometry={nodes['React-Logo_Material002_0'].geometry} material={materials['Material.002']} position={[0, 7.94, 18.1]} rotation={[0, 0, -Math.PI / 2]} scale={[39.17, 39.17, 52.73]} />
        </group>
      </group>
    </Stage>

    <OrbitControls enableZoom={false}>
    </OrbitControls>
    </Canvas>
    <p className='hidden md:block w-52 h-20 p-2 bg-white rounded absolute bottom-24 right-2 text-xs text-black font-thin'>We design products with a strong focus on both world class design and ensure your product is a market success.</p>
    </>
  )
}

useGLTF.preload('/react-transformed.glb')



